### PR TITLE
Fix ember-cli/lib/ext/promise deprecation

### PR DESCRIPTION
**Pull request by xomaczar**

### CODE REVIEW

**Comment by xomaczar** [comment]
Closes #9

**Comment by xomaczar** [comment]
ping @dschmidt

**Comment by dschmidt** [comment]
Hey there,

thanks for your PR!

I haven't dealt with yarn yet and need to look into it before I merge this. If this is urgent to you or @XaserAcheron, split it up into two PRs and I'll merge the promise fix immediately.

**Comment by XaserAcheron** [comment]
Thanks for beating me to the punch, @xomaczar ... uh, that's a positive thing. Idioms!

@dschmidt Though yarn adoption indeed ought not be part of this PR (though I'm guessing yarn.lock's inclusion was accidental), it's really not very scary at all. It's one of the odd cases where (for me, at least), a thing described as a "drop-in replacement" actually works as advertised. Weird. o_O

**Comment by xomaczar** [comment]
@dschmidt no it's not urgent - I'm using my fork. Yarn is optional - will not hurt anything, I was doing yarn on my host project and got carried away.
@XaserAcheron - no it was not accidental yarn.lock must be checked-in to ensures your-build === my-build

**Comment by XaserAcheron** [comment]
This project isn't officially using yarn yet, though. You've added an entirely new thing to the project.

**Comment by dschmidt** [comment]
... yes, I'm reluctant to check in a 4700 lines generated file without properly checking what it's good for and if the content is sane.

**Comment by XaserAcheron** [comment]
I don't wish for this to stagnate, so I've cherry-picked the fix (sans yarn.lock) and opened #11. Hope @xomaczar doesn't mind.

**Comment by lukemelia** [comment]
@dschmidt for a point of reference, I've added Yarn lockfiles to all of the ember-cli-deploy core plugins, which I help maintain. It's benefit is minor: improved consistency between various development machines and CI servers. The lockfile does not come into play at all when the package is actually used as an addon.

**Comment by xomaczar** [comment]
@XaserAcheron sure np - thx for doing it.
@lukemelia :rocket:

**Comment by dschmidt** [comment]
I looked into creating the yarn file myself, but I couldn't make it all work on current Node without updating a whole lot of other things first - so I cut a release first and will give yarn another go soon.

**Pull request closed without merging**
